### ISSUE TITLE
Sub of Function not defined, IsArrayEmpty() in AddEventListner()

### ISSUE THREAD

**Issue by Heathy65** [todar/VBA-Userform-EventListener#1]
I get a compile error "Sub of Function not defined" for the AddEventListner(), seems to not like IsArrayEmpty().  Possibly I'm doing something wrong, I'm quite new to VBA.

**Comment by todar** [comment]
You are not doing anything wrong, that is a custom function of mine, I didn't realize it was missing. I'm on my phone right now so I will have to update it once I'm on my computer. If you need that function ahead of time you can check it out in my VBA-Array functions repository. Thanks for letting me know about this error! I'll let you know once I've updated my code

**Comment by todar** [comment]
Added the function, won't have time to test it until tomorrow. Closing this issue, but please let me know if you have any other issues with the code!
