### ISSUE TITLE
Before and After

### ISSUE THREAD

**Issue by IA-Programming** [todar/VBA-Userform-EventListener#2]
I tried for my own to get the events BeforeUpdate And AfterUpdate for textbox ,but I don't get it why is not working maybe is something missing because my approach was with the event DblClick 'cause it has the same requirements it seem not to be the case then I don't no what else to do.
I'm not that newbie in VBA but in the language yes, and that's why I'm requesting this to you.
Please I need Help!
I need this Events

**Comment by todar** [comment]
It's difficult to tell why it wasn't working without an example of how you implemented the code. If you provide a simplified example of what you are attempting I can see if I can help from there.
